import type { LineItem, DeliveryType } from "@/app/_components/Dahsboard/booking/create/ProductCard";

export type OrderStatus =
  | "confirmed"
  | "behandles"
  | "active"
  | "cancelled"
  | "fail"
  | "completed"
  | "invoiced"
  | "betalt";

export type { DeliveryType } from "@/app/_components/Dahsboard/booking/create/ProductCard";
export type { LineItem } from "@/app/_components/Dahsboard/booking/create/ProductCard";

export type MonitoringOrReturn = "Monitoring" | "Return" | "Monitoring + Return" | "";

export type OrderRow = {
  id: string;
  status: OrderStatus;
  deliveryDate: string;
  timeWindow: string;
  customer: string;
  orderNo: string;
  name: string;
  phone: string;
  pickupAddress: string;
  extraPickup: string;
  deliveryAddress: string;
  returnAddress: string;
  products: string[];
  deliveryType: DeliveryType;
  monitoringOrReturn: MonitoringOrReturn;
  description: string;
  cashierName: string;
  cashierPhone: string;
  customerNotes: string;
  driverInfo: string;
  orderDate: string;
  lastEdited: string;
  priceExVat: number;
  priceSubcontractor: number;
  priceIncVat?: number;
  subcontractor: string;
  cardItems: Record<number, LineItem[]>;
  cardDeliveryType: Record<number, DeliveryType>;
  cardProducts: Record<number, string | null>;
  rabatt?: number;
  leggTil?: number;
  subcontractorMinus?: number;
  subcontractorPlus?: number;
};

export const ORDERS: OrderRow[] = [
  {
    id: "13206",
    status: "behandles",
    deliveryDate: "2026-03-03",
    timeWindow: "12:00 - 16:00",
    customer: "POWER Ski",
    orderNo: "41254802",
    name: "Ola Hansen",
    phone: "90000001",
    pickupAddress: "POWER Ski, Jernbanesvingen 6, 1400 Ski",
    extraPickup: "—",
    deliveryAddress: "Fjellveien 4, 1400 Ski",
    returnAddress: "—",
    products: ["Vaskemaskin"],
    deliveryType: "Innbæring",
    monitoringOrReturn: "",
    description: "Install washing machine.",
    cashierName: "Ali",
    cashierPhone: "+4790000001",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-01",
    lastEdited: "2026-02-02 10:00",
    priceExVat: 3079,
    priceSubcontractor: 1840,
    subcontractor: "Sub A",
    cardProducts:     { 0: "WASH" },
    cardDeliveryType: { 0: "Innbæring" },
    cardItems: {
      0: [
        { key: "INDOOR__hjemlevering_innbaering", qty: 1 },
        { key: "INSWASH1__montering_vaskemaskin_vatrom", qty: 1 },
      ],
    },
    rabatt: 200,
    leggTil: 23,
    subcontractorMinus: 222,
    subcontractorPlus: 222,
  },
  {
    id: "13207",
    status: "completed",
    deliveryDate: "2026-03-04",
    timeWindow: "08:00 - 12:00",
    customer: "POWER Rud",
    orderNo: "41254803",
    name: "Kari Olsen",
    phone: "90000002",
    pickupAddress: "POWER Rud, Rudssletta 90, 1351 Rud",
    extraPickup: "—",
    deliveryAddress: "Solbakken 7, 1351 Rud",
    returnAddress: "—",
    products: ["TV 65\""],
    deliveryType: "Innbæring",
    monitoringOrReturn: "",
    description: "Mount TV on wall.",
    cashierName: "Jonas",
    cashierPhone: "+4790000002",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-02",
    lastEdited: "2026-02-03 09:15",
    priceExVat: 2668,
    priceSubcontractor: 1450,
    subcontractor: "Sub B",
    cardProducts:     { 0: "TV" },
    cardDeliveryType: { 0: "Innbæring" },
    cardItems: {
      0: [
        { key: "INDOOR__hjemlevering_innbaering", qty: 1 },
        { key: "ONWALL2__montering_tv_over_55_vegg", qty: 1 },
      ],
    },
  },
  {
    id: "13208",
    status: "confirmed",
    deliveryDate: "2026-03-05",
    timeWindow: "16:00 - 21:00",
    customer: "POWER Skullerud",
    orderNo: "41254804",
    name: "Per Nilsen",
    phone: "90000003",
    pickupAddress: "POWER Skullerud, Olaf Helsets vei 5, 0694 Oslo",
    extraPickup: "—",
    deliveryAddress: "Bakkeveien 2, 0694 Oslo",
    returnAddress: "—",
    products: ["Kjøleskap"],
    deliveryType: "Innbæring",
    monitoringOrReturn: "",
    description: "Deliver fridge.",
    cashierName: "Emma",
    cashierPhone: "+4790000003",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-03",
    lastEdited: "2026-02-03 14:30",
    priceExVat: 1068,
    priceSubcontractor: 649,
    subcontractor: "Sub C",
    cardProducts:     { 0: "FRIDGE" },
    cardDeliveryType: { 0: "Innbæring" },
    cardItems: {
      0: [
        { key: "INDOOR__hjemlevering_innbaering", qty: 1 },
        { key: "INSFRIDGE__montering_frittstaaende_skap", qty: 1 },
      ],
    },
  },
  {
    id: "13209",
    status: "invoiced",
    deliveryDate: "2026-03-06",
    timeWindow: "12:00 - 16:00",
    customer: "POWER Rud",
    orderNo: "41254805",
    name: "Lise Berg",
    phone: "90000004",
    pickupAddress: "POWER Rud, Løxaveien 5, 1351 Rud",
    extraPickup: "—",
    deliveryAddress: "Åsveien 11, 1351 Rud",
    returnAddress: "—",
    products: ["Oppvaskmaskin"],
    deliveryType: "Innbæring",
    monitoringOrReturn: "",
    description: "Install dishwasher.",
    cashierName: "Ali",
    cashierPhone: "+4790000004",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-04",
    lastEdited: "2026-02-04 12:00",
    priceExVat: 2918,
    priceSubcontractor: 1450,
    subcontractor: "Sub A",
    cardProducts:     { 0: "DISH" },
    cardDeliveryType: { 0: "Innbæring" },
    cardItems: {
      0: [
        { key: "INDOOR__hjemlevering_innbaering", qty: 1 },
        { key: "INSDISHW2__montering_oppvaskmaskin", qty: 1 },
      ],
    },
  },
  {
    id: "13210",
    status: "cancelled",
    deliveryDate: "2026-03-07",
    timeWindow: "08:00 - 12:00",
    customer: "POWER Ski",
    orderNo: "41254806",
    name: "Thomas Vik",
    phone: "90000005",
    pickupAddress: "POWER Ski, Jernbanesvingen 6, 1400 Ski",
    extraPickup: "—",
    deliveryAddress: "Granveien 8, 1400 Ski",
    returnAddress: "—",
    products: ["Komfyr"],
    deliveryType: "Første trinn",
    monitoringOrReturn: "",
    description: "Delivery cancelled.",
    cashierName: "Jonas",
    cashierPhone: "+4790000005",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-05",
    lastEdited: "2026-02-05 11:10",
    priceExVat: 590,
    priceSubcontractor: 390,
    subcontractor: "Sub B",
    cardProducts:     { 0: "COOKER" },
    cardDeliveryType: { 0: "Første trinn" },
    cardItems: {
      0: [
        { key: "DELIVERY__frakt_til_trapp", qty: 1 },
      ],
    },
  },
  {
    id: "13211",
    status: "active",
    deliveryDate: "2026-02-25",
    timeWindow: "16:00 - 21:00",
    customer: "POWER Skullerud",
    orderNo: "41254807",
    name: "Anne Dahl",
    phone: "90000006",
    pickupAddress: "POWER Skullerud, Olaf Helsets vei 5, 0694 Oslo",
    extraPickup: "—",
    deliveryAddress: "Furuveien 3, 0694 Oslo",
    returnAddress: "—",
    products: ["TV 55\""],
    deliveryType: "Innbæring",
    monitoringOrReturn: "",
    description: "TV delivery.",
    cashierName: "Emma",
    cashierPhone: "+4790000006",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-06",
    lastEdited: "2026-02-06 15:45",
    priceExVat: 2168,
    priceSubcontractor: 1249,
    subcontractor: "Sub C",
    cardProducts:     { 0: "TV" },
    cardDeliveryType: { 0: "Innbæring" },
    cardItems: {
      0: [
        { key: "INDOOR__hjemlevering_innbaering", qty: 1 },
        { key: "ONWALL1__montering_tv_under_55_vegg", qty: 1 },
      ],
    },
  },
  {
    id: "13212",
    status: "completed",
    deliveryDate: "2026-03-09",
    timeWindow: "12:00 - 16:00",
    customer: "POWER Rud",
    orderNo: "41254808",
    name: "Marius Lund",
    phone: "90000007",
    pickupAddress: "POWER Rud, Rudssletta 90, 1351 Rud",
    extraPickup: "—",
    deliveryAddress: "Parkveien 6, 1351 Rud",
    returnAddress: "—",
    products: ["Tørketrommel"],
    deliveryType: "Innbæring",
    monitoringOrReturn: "",
    description: "Deliver dryer.",
    cashierName: "Ali",
    cashierPhone: "+4790000007",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-07",
    lastEdited: "2026-02-07 09:00",
    priceExVat: 1108,
    priceSubcontractor: 650,
    subcontractor: "Sub A",
    cardProducts:     { 0: "DRYER" },
    cardDeliveryType: { 0: "Innbæring" },
    cardItems: {
      0: [
        { key: "INDOOR__hjemlevering_innbaering", qty: 1 },
        { key: "INSDRYER__montering_torketrommel", qty: 1 },
      ],
    },
  },
  {
    id: "13213",
    status: "confirmed",
    deliveryDate: "2026-03-10",
    timeWindow: "08:00 - 12:00",
    customer: "POWER Ski",
    orderNo: "41254809",
    name: "Henrik Moe",
    phone: "90000008",
    pickupAddress: "POWER Ski, Jernbanesvingen 6, 1400 Ski",
    extraPickup: "—",
    deliveryAddress: "Fjelltoppen 12, 1400 Ski",
    returnAddress: "—",
    products: ["Kombiskap"],
    deliveryType: "Innbæring",
    monitoringOrReturn: "",
    description: "Deliver fridge/freezer.",
    cashierName: "Jonas",
    cashierPhone: "+4790000008",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-08",
    lastEdited: "2026-02-08 10:30",
    priceExVat: 1068,
    priceSubcontractor: 649,
    subcontractor: "Sub B",
    cardProducts:     { 0: "FRIDGE" },
    cardDeliveryType: { 0: "Innbæring" },
    cardItems: {
      0: [
        { key: "INDOOR__hjemlevering_innbaering", qty: 1 },
        { key: "INSFRIDGE__montering_frittstaaende_skap", qty: 1 },
      ],
    },
  },
  {
    id: "13214",
    status: "betalt",
    deliveryDate: "2026-03-22",
    timeWindow: "16:00 - 21:00",
    customer: "POWER Skullerud",
    orderNo: "41254810",
    name: "Sara Lie",
    phone: "90000009",
    pickupAddress: "POWER Skullerud, Olaf Helsets vei 5, 0694 Oslo",
    extraPickup: "—",
    deliveryAddress: "Solheim 9, 0694 Oslo",
    returnAddress: "—",
    products: ["Oppvaskmaskin"],
    deliveryType: "Innbæring",
    monitoringOrReturn: "",
    description: "Install dishwasher.",
    cashierName: "Emma",
    cashierPhone: "+4790000009",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-09",
    lastEdited: "2026-02-09 16:20",
    priceExVat: 2918,
    priceSubcontractor: 1450,
    subcontractor: "Sub C",
    cardProducts:     { 0: "DISH" },
    cardDeliveryType: { 0: "Innbæring" },
    cardItems: {
      0: [
        { key: "INDOOR__hjemlevering_innbaering", qty: 1 },
        { key: "INSDISHW2__montering_oppvaskmaskin", qty: 1 },
      ],
    },
  },
  {
    id: "13215",
    status: "fail",
    deliveryDate: "2026-03-15",
    timeWindow: "12:00 - 16:00",
    customer: "POWER Rud",
    orderNo: "41254811",
    name: "Daniel Holm",
    phone: "90000010",
    pickupAddress: "POWER Rud, Løxaveien 5, 1351 Rud",
    extraPickup: "—",
    deliveryAddress: "Engveien 14, 1351 Rud",
    returnAddress: "—",
    products: ["Komfyr"],
    deliveryType: "Første trinn",
    monitoringOrReturn: "",
    description: "Customer not home.",
    cashierName: "Ali",
    cashierPhone: "+4790000010",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-10",
    lastEdited: "2026-02-10 13:45",
    priceExVat: 590,
    priceSubcontractor: 390,
    subcontractor: "Sub A",
    cardProducts:     { 0: "COOKER" },
    cardDeliveryType: { 0: "Første trinn" },
    cardItems: {
      0: [
        { key: "DELIVERY__frakt_til_trapp", qty: 1 },
        { key: "NOTHOME__bomtur_ikke_hjemme", qty: 1 },
      ],
    },
  },
  {
    id: "3231",
    status: "fail",
    deliveryDate: "",
    timeWindow: "12:00 - 16:00",
    customer: "POWER Rud",
    orderNo: "41254811",
    name: "Daniel Holm",
    phone: "90000010",
    pickupAddress: "POWER Rud, Løxaveien 5, 1351 Rud",
    extraPickup: "—",
    deliveryAddress: "Engveien 14, 1351 Rud",
    returnAddress: "—",
    products: ["Komfyr"],
    deliveryType: "Første trinn",
    monitoringOrReturn: "",
    description: "Customer not home.",
    cashierName: "Ali",
    cashierPhone: "+4790000010",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-10",
    lastEdited: "2026-02-10 13:45",
    priceExVat: 590,
    priceSubcontractor: 390,
    subcontractor: "Sub A",
    cardProducts:     { 0: "COOKER" },
    cardDeliveryType: { 0: "Første trinn" },
    cardItems: {
      0: [
        { key: "DELIVERY__frakt_til_trapp", qty: 1 },
      ],
    },
  },
  {
    id: "23",
    status: "fail",
    deliveryDate: "2026-03-12",
    timeWindow: "12:00 - 16:00",
    customer: "POWER Rud",
    orderNo: "41254811",
    name: "Daniel Holm",
    phone: "90000010",
    pickupAddress: "POWER Rud, Løxaveien 5, 1351 Rud",
    extraPickup: "—",
    deliveryAddress: "Engveien 14, 1351 Rud",
    returnAddress: "—",
    products: ["Komfyr"],
    deliveryType: "Første trinn",
    monitoringOrReturn: "",
    description: "Customer not home.",
    cashierName: "Ali",
    cashierPhone: "+4790000010",
    customerNotes: "",
    driverInfo: "",
    orderDate: "2026-02-10",
    lastEdited: "2026-02-10 13:45",
    priceExVat: 590,
    priceSubcontractor: 390,
    subcontractor: "Sub A",
    cardProducts:     { 0: "COOKER" },
    cardDeliveryType: { 0: "Første trinn" },
    cardItems: {
      0: [
        { key: "DELIVERY__frakt_til_trapp", qty: 1 },
      ],
    },
  },
];

export function toExportRow(o: OrderRow) {
  return {
    ID: o.id,
    Status: o.status,
    "Delivery date": o.deliveryDate,
    "Time window": o.timeWindow,
    customer: o.customer,
    "Order no.": o.orderNo,
    Name: o.name,
    Phone: o.phone,
    "Pickup address": o.pickupAddress,
    "Extra pickup": o.extraPickup,
    "Delivery address": o.deliveryAddress,
    "Return address": o.returnAddress,
    Products: o.products.join(", "),
    "Delivery type": o.deliveryType,
    "Monitoring/ return": o.monitoringOrReturn,
    Description: o.description,
    "Cashier name": o.cashierName,
    "Cashier phone": o.cashierPhone,
    "Customer notes": o.customerNotes,
    "Driver info": o.driverInfo,
    "Order date": o.orderDate,
    "Last edited": o.lastEdited,
    "Price ex VAT": o.priceExVat,
    "Price subcontractor": o.priceSubcontractor,
    Subcontractor: o.subcontractor,
  };
}