// app/_mockdb/orders.ts
// Mock “database” for orders + a typed shape that matches your export columns.

export type OrderStatus =
  | "inProgress"
  | "confirmed"
  | "active"
  | "cancelled"
  | "fail"
  | "completed"
  | "invoiced"
  | "betalt";

export type DeliveryType = "Innbæring" | "Uten innbæring" | "Bærehjelp" | "";
export type MonitoringOrReturn = "Monitoring" | "Return" | "Monitoring + Return" | "";

export type OrderRow = {
  // --- Export columns (in your order) ---
  id: string; // ID
  status: OrderStatus; // Status
  deliveryDate: string; // Delivery date (YYYY-MM-DD)
  timeWindow: string; // Time window (e.g. "16:00 - 21:00")

  client: string; // Customer (e.g. "POWER Rud")
  orderNo: string; // Order no.
  name: string; // Name
  phone: string; // Phone

  pickupAddress: string; // Pickup address
  extraPickup: string; // Extra pickup (or "—")
  deliveryAddress: string; // Delivery address
  returnAddress: string; // Return address (or "—")

  products: string[]; // Products (array; export as comma-separated)
  deliveryType: DeliveryType; // Delivery type

  monitoringOrReturn: MonitoringOrReturn; // Monitoring/ return
  description: string; // Description

  cashierName: string; // Cashier name
  cashierPhone: string; // Cashier phone

  customerNotes: string; // Customer notes
  driverInfo: string; // Driver info
  orderDate: string; // Order date (YYYY-MM-DD)
  lastEdited: string; // Last edited (YYYY-MM-DD HH:mm)

  priceExVat: number; // Price ex VAT
  priceIncVat?: number; // optional, if you want
  subcontractor: string; // subcontractor
};

// Example rows (add as many as you want)
export const ORDERS: OrderRow[] = [
  {
  id: "13206",
  status: "active",
  deliveryDate: "2026-03-03",
  timeWindow: "12:00 - 16:00",
  client: "POWER Ski",
  orderNo: "41254802",
  name: "Ola Hansen",
  phone: "90000001",
  pickupAddress: "POWER Ski, Jernbanesvingen 6, 1400 Ski",
  extraPickup: "—",
  deliveryAddress: "Fjellveien 4, 1400 Ski",
  returnAddress: "—",
  products: ["Vaskemaskin"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Install washing machine.",
  cashierName: "Ali",
  cashierPhone: "+4790000001",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-01",
  lastEdited: "2026-02-02 10:00",
  priceExVat: 2500,
  subcontractor: "Sub A",
},
{
  id: "13207",
  status: "completed",
  deliveryDate: "2026-03-04",
  timeWindow: "08:00 - 12:00",
  client: "POWER Rud",
  orderNo: "41254803",
  name: "Kari Olsen",
  phone: "90000002",
  pickupAddress: "POWER Rud, Rudssletta 90, 1351 Rud",
  extraPickup: "—",
  deliveryAddress: "Solbakken 7, 1351 Rud",
  returnAddress: "—",
  products: ["TV 65\""],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Mount TV on wall.",
  cashierName: "Jonas",
  cashierPhone: "+4790000002",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-02",
  lastEdited: "2026-02-03 09:15",
  priceExVat: 3200,
  subcontractor: "Sub B",
},
{
  id: "13208",
  status: "confirmed",
  deliveryDate: "2026-03-05",
  timeWindow: "16:00 - 21:00",
  client: "POWER Skullerud",
  orderNo: "41254804",
  name: "Per Nilsen",
  phone: "90000003",
  pickupAddress: "POWER Skullerud, Olaf Helsets vei 5, 0694 Oslo",
  extraPickup: "—",
  deliveryAddress: "Bakkeveien 2, 0694 Oslo",
  returnAddress: "—",
  products: ["Kjøleskap"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Deliver fridge.",
  cashierName: "Emma",
  cashierPhone: "+4790000003",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-03",
  lastEdited: "2026-02-03 14:30",
  priceExVat: 2100,
  subcontractor: "Sub C",
},
{
  id: "13209",
  status: "invoiced",
  deliveryDate: "2026-03-06",
  timeWindow: "12:00 - 16:00",
  client: "POWER Rud",
  orderNo: "41254805",
  name: "Lise Berg",
  phone: "90000004",
  pickupAddress: "POWER Rud, Løxaveien 5, 1351 Rud",
  extraPickup: "—",
  deliveryAddress: "Åsveien 11, 1351 Rud",
  returnAddress: "—",
  products: ["Oppvaskmaskin"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Install dishwasher.",
  cashierName: "Ali",
  cashierPhone: "+4790000004",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-04",
  lastEdited: "2026-02-04 12:00",
  priceExVat: 2800,
  subcontractor: "Sub A",
},
{
  id: "13210",
  status: "cancelled",
  deliveryDate: "2026-03-07",
  timeWindow: "08:00 - 12:00",
  client: "POWER Ski",
  orderNo: "41254806",
  name: "Thomas Vik",
  phone: "90000005",
  pickupAddress: "POWER Ski, Jernbanesvingen 6, 1400 Ski",
  extraPickup: "—",
  deliveryAddress: "Granveien 8, 1400 Ski",
  returnAddress: "—",
  products: ["Komfyr"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Delivery cancelled.",
  cashierName: "Jonas",
  cashierPhone: "+4790000005",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-05",
  lastEdited: "2026-02-05 11:10",
  priceExVat: 0,
  subcontractor: "Sub B",
},
{
  id: "13211",
  status: "active",
  deliveryDate: "2026-03-08",
  timeWindow: "16:00 - 21:00",
  client: "POWER Skullerud",
  orderNo: "41254807",
  name: "Anne Dahl",
  phone: "90000006",
  pickupAddress: "POWER Skullerud, Olaf Helsets vei 5, 0694 Oslo",
  extraPickup: "—",
  deliveryAddress: "Furuveien 3, 0694 Oslo",
  returnAddress: "—",
  products: ["TV 55\""],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "TV delivery.",
  cashierName: "Emma",
  cashierPhone: "+4790000006",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-06",
  lastEdited: "2026-02-06 15:45",
  priceExVat: 2900,
  subcontractor: "Sub C",
},
{
  id: "13212",
  status: "completed",
  deliveryDate: "2026-03-09",
  timeWindow: "12:00 - 16:00",
  client: "POWER Rud",
  orderNo: "41254808",
  name: "Marius Lund",
  phone: "90000007",
  pickupAddress: "POWER Rud, Rudssletta 90, 1351 Rud",
  extraPickup: "—",
  deliveryAddress: "Parkveien 6, 1351 Rud",
  returnAddress: "—",
  products: ["Tørketrommel"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Deliver dryer.",
  cashierName: "Ali",
  cashierPhone: "+4790000007",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-07",
  lastEdited: "2026-02-07 09:00",
  priceExVat: 2400,
  subcontractor: "Sub A",
},
{
  id: "13213",
  status: "confirmed",
  deliveryDate: "2026-03-10",
  timeWindow: "08:00 - 12:00",
  client: "POWER Ski",
  orderNo: "41254809",
  name: "Henrik Moe",
  phone: "90000008",
  pickupAddress: "POWER Ski, Jernbanesvingen 6, 1400 Ski",
  extraPickup: "—",
  deliveryAddress: "Fjelltoppen 12, 1400 Ski",
  returnAddress: "—",
  products: ["Kombiskap"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Deliver fridge/freezer.",
  cashierName: "Jonas",
  cashierPhone: "+4790000008",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-08",
  lastEdited: "2026-02-08 10:30",
  priceExVat: 2600,
  subcontractor: "Sub B",
},
{
  id: "13214",
  status: "betalt",
  deliveryDate: "2026-03-11",
  timeWindow: "16:00 - 21:00",
  client: "POWER Skullerud",
  orderNo: "41254810",
  name: "Sara Lie",
  phone: "90000009",
  pickupAddress: "POWER Skullerud, Olaf Helsets vei 5, 0694 Oslo",
  extraPickup: "—",
  deliveryAddress: "Solheim 9, 0694 Oslo",
  returnAddress: "—",
  products: ["Oppvaskmaskin"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Install dishwasher.",
  cashierName: "Emma",
  cashierPhone: "+4790000009",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-09",
  lastEdited: "2026-02-09 16:20",
  priceExVat: 3000,
  subcontractor: "Sub C",
},
{
  id: "13215",
  status: "fail",
  deliveryDate: "2026-03-12",
  timeWindow: "12:00 - 16:00",
  client: "POWER Rud",
  orderNo: "41254811",
  name: "Daniel Holm",
  phone: "90000010",
  pickupAddress: "POWER Rud, Løxaveien 5, 1351 Rud",
  extraPickup: "—",
  deliveryAddress: "Engveien 14, 1351 Rud",
  returnAddress: "—",
  products: ["Komfyr"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Customer not home.",
  cashierName: "Ali",
  cashierPhone: "+4790000010",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-10",
  lastEdited: "2026-02-10 13:45",
  priceExVat: 0,
  subcontractor: "Sub A",
},
{
  id: "3231",
  status: "fail",
  deliveryDate: "2026-03-12",
  timeWindow: "12:00 - 16:00",
  client: "POWER Rud",
  orderNo: "41254811",
  name: "Daniel Holm",
  phone: "90000010",
  pickupAddress: "POWER Rud, Løxaveien 5, 1351 Rud",
  extraPickup: "—",
  deliveryAddress: "Engveien 14, 1351 Rud",
  returnAddress: "—",
  products: ["Komfyr"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Customer not home.",
  cashierName: "Ali",
  cashierPhone: "+4790000010",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-10",
  lastEdited: "2026-02-10 13:45",
  priceExVat: 0,
  subcontractor: "Sub A",
},
{
  id: "23",
  status: "fail",
  deliveryDate: "2026-03-12",
  timeWindow: "12:00 - 16:00",
  client: "POWER Rud",
  orderNo: "41254811",
  name: "Daniel Holm",
  phone: "90000010",
  pickupAddress: "POWER Rud, Løxaveien 5, 1351 Rud",
  extraPickup: "—",
  deliveryAddress: "Engveien 14, 1351 Rud",
  returnAddress: "—",
  products: ["Komfyr"],
  deliveryType: "Innbæring",
  monitoringOrReturn: "",
  description: "Customer not home.",
  cashierName: "Ali",
  cashierPhone: "+4790000010",
  customerNotes: "",
  driverInfo: "",
  orderDate: "2026-02-10",
  lastEdited: "2026-02-10 13:45",
  priceExVat: 0,
  subcontractor: "Sub A",
}
];

export function toExportRow(o: OrderRow) {
  return {
    ID: o.id,
    Status: o.status,
    "Delivery date": o.deliveryDate,
    "Time window": o.timeWindow,
    client: o.client,
    "Order no.": o.orderNo,
    Name: o.name,
    Phone: o.phone,
    "Pickup address": o.pickupAddress,
    "Extra pickup": o.extraPickup,
    "Delivery address": o.deliveryAddress,
    "Return address": o.returnAddress,
    Products: o.products.join(", "),
    "Delivery type": o.deliveryType,
    "Monitoring/ return": o.monitoringOrReturn,
    Description: o.description,
    "Cashier name": o.cashierName,
    "Cashier phone": o.cashierPhone,
    "Customer notes": o.customerNotes,
    "Driver info": o.driverInfo,
    "Order date": o.orderDate,
    "Last edited": o.lastEdited,
    "Price ex VAT": o.priceExVat,
    Subcontractor: o.subcontractor,
  };
}