import { VehicleProps } from "@/app/_components/site/VehicleRental/VehicleCard";

export const vehicles: VehicleProps[] = [
  {
    id: 1,
    name: "Renault Master Box",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/Renault-master-box.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(39).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(36).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(35).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(1).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(11).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(8).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(5).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(7).jpeg",
    ],
    extraImages: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(9).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(10).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(12).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(13).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(14).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(15).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(16).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(17).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(18).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(19).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(20).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(21).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(22).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(23).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(24).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(25).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(26).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(27).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(28).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(29).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(30).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(31).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(32).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(33).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(34).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(37).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(38).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(40).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(41).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(42).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/AS54813/renault-master-box-img+(43).jpeg",
    ],
    description: {
      en: "The Renault Master box van is a 19 m2 diesel van for larger transport jobs in Oslo. With 3 seats, manual gearbox, reversing camera, cruise control, and lift equipment, it is suited for moving, deliveries, and equipment transport where loading capacity matters.",
      no: "Renault Master kassebil er en 19 m2 dieselvarebil for større transportoppdrag i Oslo. Med 3 seter, manuell girkasse, ryggekamera, cruisekontroll og liftutstyr passer den godt til flytting, leveranser og transport av utstyr der lastekapasitet er viktig.",
    },
    features: [
      { en: "19 m2 cargo area", no: "19 m2 lasterom" },
      { en: "Reversing camera", no: "Ryggekamera" },
      { en: "Cruise control", no: "Cruisekontroll" },
      { en: "Lift equipment", no: "Liftutstyr" },
    ],
    year: 2017,
    location: "Oslo",
    fuelType: "Diesel",
    vehicleType: "Van",
    gearbox: "Manual",
    listingType: "rental",
    extraKmPrice: 2.5,
    pricePerDay: 1800,
    price: 139000,
    finnLink: "",
    vegvesenLink: "https://www.vegvesen.no/en/vehicles/buy-and-sell/vehicle-information/check-vehicle-information/?registreringsnummer=AS54813",
  },
  {
    id: 2,
    name: "Citroen BERL-LA 90 EHDI",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen+BERLA+EHDI.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(11).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(9).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(10).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(5).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(8).jpeg",
    ],
    extraImages: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(7).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(4).jpeg",
    ],
    description: {
      en: "The Citroen BERL-LA 90 EHDI is a compact diesel van in Alesund for city driving, courier work, and small delivery jobs. It has 3 seats, manual gearbox, and cruise control, making it practical for daily transport where easy parking and low running costs matter.",
      no: "Citroen BERL-LA 90 EHDI er en kompakt dieselvarebil i Ålesund for bykjøring, budoppdrag og mindre leveranser. Den har 3 seter, manuell girkasse og cruisekontroll, som gjør den praktisk til daglig transport der enkel parkering og lave driftskostnader er viktig.",
    },
    features: [
      { en: "Compact and city-friendly", no: "Kompakt og byvennlig" },
      { en: "Cruise control", no: "Cruisekontroll" },
      { en: "Fuel-efficient diesel engine", no: "Drivstoffeffektiv dieselmotor" },
      { en: "Easy to park and maneuver", no: "Enkel å parkere og manøvrere" },
    ],
    year: 2013,
    location: "Ålesund",
    fuelType: "Diesel",
    vehicleType: "Van",
    gearbox: "Manual",
    listingType: "rental",
    extraKmPrice: 2.5,
    price: 20000,
    pricePerDay: 500,
    finnLink: "",
    vegvesenLink: "https://www.vegvesen.no/en/vehicles/buy-and-sell/vehicle-information/check-vehicle-information/?registreringsnummer=DP35573",
  },
  {
    id: 3,
    name: "Opel Vivaro 1.9 DTI 2900",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+2900.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(5).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(7).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(4).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(1).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(6).jpeg",
    ],
    description: {
      en: "The Opel Vivaro 1.9 DTI 2900 is a reliable diesel van in Alesund for practical transport work. With 3 seats and a manual gearbox, it is suited for deliveries, equipment transport, courier routes, and smaller moving jobs.",
      no: "Opel Vivaro 1.9 DTI 2900 er en pålitelig dieselvarebil i Ålesund for praktiske transportoppdrag. Med 3 seter og manuell girkasse passer den godt til leveranser, transport av utstyr, budruter og mindre flyttejobber.",
    },
    features: [
      { en: "Reliable diesel engine", no: "Pålitelig dieselmotor" },
      { en: "Suitable for deliveries and courier work", no: "Passer til leveranser og budruter" },
    ],
    year: 2006,
    location: "Ålesund",
    fuelType: "Diesel",
    vehicleType: "Van",
    gearbox: "Manual",
    listingType: "rental",
    extraKmPrice: 2.5,
    price: 40000,
    pricePerDay: 800,
    finnLink: "",
    vegvesenLink: "https://www.vegvesen.no/en/vehicles/buy-and-sell/vehicle-information/check-vehicle-information/?registreringsnummer=UN28325",
  },
  {
    id: 4,
    name: "Ford Transit Electric",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/Ford+master+electric.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EE37508/Ford+master+electric+img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EE37508/Ford+master+electric+img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EE37508/Ford+master+electric+img+(7).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EE37508/Ford+master+electric+img+(9).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EE37508/Ford+master+electric+img+(8).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EE37508/Ford+master+electric+img+(1).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EE37508/Ford+master+electric+img+(2).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EE37508/Ford+master+electric+img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EE37508/Ford+master+electric+img+(5).jpeg",
    ],
    extraImages: [],
    description: {
      en: "The Ford Transit is a 2023 automatic diesel van in Oslo with lift equipment. With 3 seats and a modern drivetrain, it is suited for professional transport, deliveries, and moving jobs that need dependable loading support.",
      no: "Ford Transit er en 2023-modell automat dieselvarebil i Oslo med liftutstyr. Med 3 seter og moderne drivlinje passer den godt til profesjonell transport, leveranser og flytteoppdrag som krever god lastehjelp.",
    },
    features: [
      { en: "Lift equipment", no: "Liftutstyr" },
      { en: "Modern 2023 model", no: "Moderne 2023-modell" },
    ],
    year: 2023,
    location: "Oslo",
    fuelType: "Electric",
    vehicleType: "Van",
    gearbox: "Automatic",
    listingType: "rental",
    extraKmPrice: 2.5,
    pricePerDay: 1250,
    price: 399000,
    finnLink: "",
    vegvesenLink: "https://www.vegvesen.no/en/vehicles/buy-and-sell/vehicle-information/check-vehicle-information/?registreringsnummer=EE37508",
  },
  {
    id: 5,
    name: "Ford Transit",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Transit/Ford-transit-boxy.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Transit/DP63137/Ford-transit-img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Transit/DP63137/Ford-transit-img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Transit/DP63137/Ford-transit-img.jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Transit/DP63137/Ford-transit-img+(1).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Transit/DP63137/Ford-transit-img+(2).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Transit/DP63137/Ford-transit-img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Transit/DP63137/Ford-transit-img+(5).jpeg",
    ],
    extraImages: [],
    description: {
      en: "The Ford Transit is a 2014 manual diesel box van in Oslo with a 19 m2 cargo area, cruise control, 3 seats, and lift equipment. It is built for larger deliveries, moving assignments, and heavy everyday transport.",
      no: "Ford Transit er en 2014-modell manuell diesel kassebil i Oslo med 19 m2 lasterom, cruisekontroll, 3 seter og liftutstyr. Den er laget for større leveranser, flytteoppdrag og tung daglig transport.",
    },
    features: [
      { en: "19 m2 cargo area", no: "19 m2 lasterom" },
      { en: "Cruise control", no: "Cruisekontroll" },
      { en: "Lift equipment", no: "Liftutstyr" },
    ],
    year: 2014,
    location: "Oslo",
    fuelType: "Diesel",
    vehicleType: "Van",
    gearbox: "Manual",
    listingType: "rental",
    extraKmPrice: 2.5,
    pricePerDay: 1500,
    price: 119000,
    finnLink: "",
    vegvesenLink: "https://www.vegvesen.no/en/vehicles/buy-and-sell/vehicle-information/check-vehicle-information/?registreringsnummer=DP63137",
  },
  {
    id: 6,
    name: "Ford Transit Electric",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/Ford+master+electric.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EB89241/Ford+master+electric+img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EB89241/Ford+master+electric+img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EB89241/Ford+master+electric+img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EB89241/Ford+master+electric+img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EB89241/Ford+master+electric+img+(1).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EB89241/Ford+master+electric+img+(5).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Ford+Master+Electric/EB89241/Ford+master+electric+img+(7).jpeg",
    ],
    extraImages: [],
    description: {
      en: "The Ford Transit is a 2022 automatic diesel van in Alesund with 3 seats, full specification, navigation. It is a strong option for professional delivery routes, business transport, and moving work.",
      no: "Ford Transit er en 2022-modell automat dieselvarebil i Ålesund med 3 seter, full utstyrspakke, navigasjon. Den er et godt valg for profesjonelle leveringsruter, firmatransport og flytteoppdrag.",
    },
    features: [{ en: "No lift equipment", no: "Uten Liftutstyr" }],
    year: 2022,
    location: "Ålesund",
    fuelType: "Electric",
    vehicleType: "Van",
    gearbox: "Automatic",
    listingType: "rental",
    extraKmPrice: 2.5,
    pricePerDay: 1500,
    price: 420000,
    finnLink: "",
    vegvesenLink: "https://www.vegvesen.no/en/vehicles/buy-and-sell/vehicle-information/check-vehicle-information/?registreringsnummer=EB89241",
  },
  {
    id: 7,
    name: "Renault Master Box",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/Renault-master-box.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(10).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(9).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(11).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(6).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(1).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(5).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(7).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(8).jpeg",

      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/SV80246/renault-master-box-img+(12).jpeg",
    ],
    extraImages: [],
    description: {
      en: "The Renault Master is a manual diesel 19 m2 box van used in Oslo and Alesund. With 3 seats, cruise control, reversing camera, and lift equipment, it is well suited for larger deliveries and moving assignments.",
      no: "Renault Master er en manuell diesel kassebil på 19 m2 som brukes i Oslo og Ålesund. Med 3 seter, cruisekontroll, ryggekamera og liftutstyr passer den godt til større leveranser og flytteoppdrag.",
    },
    features: [
      { en: "19 m2 cargo area", no: "19 m2 lasterom" },
      { en: "Cruise control", no: "Cruisekontroll" },
      { en: "Reversing camera", no: "Ryggekamera" },
      { en: "Lift equipment", no: "Liftutstyr" },
    ],
    year: 2017,
    location: "Ålesund",
    fuelType: "Diesel",
    vehicleType: "Van",
    gearbox: "Manual",
    listingType: "rental",
    extraKmPrice: 2.5,
    pricePerDay: 1800,
    price: 139000,
    finnLink: "",
    vegvesenLink: "https://www.vegvesen.no/en/vehicles/buy-and-sell/vehicle-information/check-vehicle-information/?registreringsnummer=SV80246",
  },
  {
    id: 8,
    name: "Volkswagen Crafter",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/Volkswagen-crafter-boxy.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(7).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(21).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(1).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(5).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(8).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(12).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(14).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(16).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(22).jpeg",
    ],
    extraImages: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(9).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(10).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(11).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(13).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(15).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(17).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(18).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(19).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Volkswagen+Crafter/LS91979/Volkswagen-crafter-img+(20).jpeg",
    ],
    description: {
      en: "The Volkswagen Crafter is a 2015 manual diesel box van in Oslo with a 19 m2 cargo area, 3 seats, reversing camera, and lift equipment. It is a practical choice for moving, deliveries, and equipment transport.",
      no: "Volkswagen Crafter er en 2015-modell manuell diesel kassebil i Oslo med 19 m2 lasterom, 3 seter, ryggekamera og liftutstyr. Den er et praktisk valg for flytting, leveranser og transport av utstyr.",
    },
    features: [
      { en: "19 m2 cargo area", no: "19 m2 lasterom" },
      { en: "Reversing camera", no: "Ryggekamera" },
      { en: "Lift equipment", no: "Liftutstyr" },
      { en: "Located in Oslo", no: "Lokalisert i Oslo" },
    ],
    year: 2015,
    location: "Oslo",
    fuelType: "Diesel",
    vehicleType: "Van",
    gearbox: "Manual",
    listingType: "rental",
    extraKmPrice: 2.5,
    pricePerDay: 1500,
    price: 120000,
    finnLink: "",
    vegvesenLink: "https://www.vegvesen.no/en/vehicles/buy-and-sell/vehicle-information/check-vehicle-information/?registreringsnummer=LS91979",
  },
  {
    id: 9,
    name: "Tesla Model Y",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/Tesla+model+y.jpg",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(5).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(1).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(7).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(8).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(9).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(10).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/tesla+model+y/EC97409/tesla-model-y-img+(11).jpeg",
    ],
    extraImages: [],
    description: {
      en: "The Tesla Model Y is a 2021 all-electric family SUV in Oslo with automatic transmission, a spacious interior, advanced safety features, and excellent driving comfort. It is an ideal choice for family trips, business travel, and everyday driving.",
      no: "Tesla Model Y er en 2021-modell helelektrisk familiebil i Oslo med automatgir, romslig kupé, avanserte sikkerhetsfunksjoner og høy kjørekomfort. Den er et ideelt valg for familieturer, forretningsreiser og daglig kjøring.",
    },
    features: [
      { en: "Long electric range - 500km", no: "Lang elektrisk rekkevidde - 500km" },
      { en: "Automatic transmission", no: "Automatgir" },
      { en: "Premium driving comfort", no: "Høy kjørekomfort" },
      { en: "Advanced safety systems", no: "Avanserte sikkerhetssystemer" },
    ],
    year: 2021,
    location: "Oslo",
    fuelType: "Electric",
    vehicleType: "Family Car",
    gearbox: "Automatic",
    listingType: "rental",
    extraKmPrice: 2.5,
    pricePerDay: 999,
    price: 350000,
    finnLink: "",
    vegvesenLink: "https://www.vegvesen.no/en/vehicles/buy-and-sell/vehicle-information/check-vehicle-information/?registreringsnummer=EC97409",
  },
];
