import { VehicleProps } from "@/app/_components/site/VehicleRental/VehicleCard";

export const vehicles: VehicleProps[] = [
  {
    id: 1,
    name: "Renault Master box van",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/Renault-master-box.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/Renault-master-box.png",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(1).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(5).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(7).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(8).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(9).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(10).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(11).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(12).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(13).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(14).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(15).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(16).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(17).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(18).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(19).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(20).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(21).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(22).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(23).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(24).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(25).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(26).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(27).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(28).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(29).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(30).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(31).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(32).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(33).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(34).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(35).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(36).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(37).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(38).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(39).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(40).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(41).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(42).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Renault-master-box/renault-master-box-img+(43).jpeg",
    ],
    description: {
      en: "The Renault Master Box Van is a spacious and reliable cargo van built for heavy-duty work. With a large load area, automatic gearbox, and a powerful diesel engine, it handles everything from furniture removals to large equipment transport with ease. Ideal for businesses and individuals who need serious hauling capacity without sacrificing driveability.",
      no: "Renault Master Box Van er en romslig og pålitelig varebil bygget for krevende arbeidsoppgaver. Med et stort lastevolum, automatisk girkasse og en kraftig dieselmotor, håndterer den alt fra møbelflytting til transport av tungt utstyr uten problemer. Perfekt for bedrifter og privatpersoner som trenger skikkelig lastekapasitet uten å gå på kompromiss med kjørekomforten.",
    },
    seats: 3,
    fuelType: "Diesel",
    vehicleType: "Van",
    gearbox: "Automatic",
    listingType: "rental",
    extraKmPrice: 0,
    pricePerDay: 0,
  },
  {
    id: 2,
    name: "Citroen BERL-LA 90 EHDI",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI.png",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(1).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(5).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(7).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(8).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(9).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(10).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Citroen-BERLA-90-EHDI/Citroen-BERLA-EHDI-img+(11).jpeg",
    ],
    description: {
      en: "The Citroen BERL-LA 90 EHDI is a practical and fuel-efficient van suited for city driving, small deliveries, courier work, and light moving jobs. Its compact size makes it easy to park and maneuver, while the 3-seat cabin and diesel manual drivetrain make it a reliable choice for everyday transport needs.",
      no: "Citroen BERL-LA 90 EHDI er en praktisk og drivstoffeffektiv varebil som passer godt til bykjøring, mindre leveranser, budoppdrag og lette flyttejobber. Den kompakte størrelsen gjør den enkel å parkere og manøvrere, mens 3-seters førerhus, dieselmotor og manuell girkasse gjør den til et pålitelig valg for daglig transport.",
    },
    seats: 3,
    fuelType: "Diesel",
    vehicleType: "Van",
    gearbox: "Manual",
    listingType: "rental",
    extraKmPrice: 0,
    pricePerDay: 0,
  },
  {
    id: 3,
    name: "Opel Vivaro 1.9 DTI 2900",
    imageUrl: "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900.png",
    images: [
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900.png",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(1).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(2).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(3).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(4).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(5).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(6).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(7).jpeg",
      "https://public-otman-img.s3.eu-north-1.amazonaws.com/Car-rental/Opel+Vivaro+1.9+DTI+2900/Opel+Vivaro+1.9+DTI+2900-img+(8).jpeg",
    ],
    description: {
      en: "The Opel Vivaro 1.9 DTI 2900 is a reliable and spacious diesel van built for practical transport work. With 3 seats, a manual gearbox, and a useful cargo area, it is well suited for deliveries, equipment transport, courier routes, and small moving jobs. It offers a good balance of space, durability, and everyday drivability.",
      no: "Opel Vivaro 1.9 DTI 2900 er en pålitelig og romslig dieselvarebil laget for praktiske transportoppdrag. Med 3 seter, manuell girkasse og et nyttig lasterom passer den godt til leveranser, transport av utstyr, budruter og mindre flyttejobber. Den gir en god kombinasjon av plass, driftssikkerhet og enkel hverdagskjøring.",
    },
    seats: 3,
    fuelType: "Diesel",
    vehicleType: "Van",
    gearbox: "Manual",
    listingType: "rental",
    extraKmPrice: 0,
    pricePerDay: 0,
  },
];
