export type BookingUiLocale = "en" | "nb";

const NB_TEXT: Record<string, string> = {
  "Add additional pickup": "Legg til ekstra hentested",
  "Add extra products": "Legg til flere produkter",
  "Additional customer's phone": "Ekstra kundetelefon",
  "Additional pickup locations": "Ekstra hentesteder",
  "All statuses": "Alle statuser",
  "Apply bulk update": "Bruk masseendring",
  "Applying...": "Bruker...",
  "All stores": "Alle butikker",
  "All subcontractors": "Alle underleverandører",
  Alerts: "Varsler",
  "Attachments": "Vedlegg",
  "Booking system": "Bestillingssystem",
  "Booking orders": "Bestillinger",
  Calculator: "Kalkulator",
  "Cashier name": "Kasserers navn",
  "Cashier phone": "Kasserers telefon",
  "Cashier's name": "Kasserers navn",
  "Cashier's phone": "Kasserers telefon",
  "Choose": "Velg",
  "Choose attachment": "Velg vedlegg",
  "Choose product": "Velg produkt",
  "Choose receipt": "Velg kvittering",
  "Choose delivery type": "Velg leveringstype",
  Close: "Lukk",
  "Clear dates": "Tøm datoer",
  "Clear selection": "Tøm utvalg",
  "Contact customer?": "Kontakt kunde?",
  "Contact note": "Kontaktnotat",
  "Create Order": "Opprett bestilling",
  "Create booking": "Opprett bestilling",
  "Custom Hours": "Custom Hours",
  "Custom time requires both from and to": "Egendefinert tid krever både fra og til",
  "Customer phone is required": "Kundens telefon er påkrevd",
  "Customer comments": "Kundekommentarer",
  "Customer name": "Kundenavn",
  "Customer notes": "Kundenotater",
  "Customer's email": "Kundens e-post",
  "Customer's name": "Kundens navn",
  "Customer's phone": "Kundens telefon",
  "Created at": "Opprettet",
  Custom: "Egendefinert",
  "Custom section": "Egendefinert seksjon",
  Dates: "Datoer",
  Description: "Beskrivelse",
  "Delivery Time window": "Levering tidsvindu",
  "Delivery address": "Leveringsadresse",
  "Delivery date": "Leveringsdato",
  "Delete order": "Slett bestilling",
  "Delete this order?": "Slette denne bestillingen?",
  "Deleting...": "Sletter...",
  Download: "Last ned",
  "Delivery date cannot be in the past.": "Leveringsdato kan ikke være i fortiden.",
  "Delivery date is required.": "Leveringsdato er påkrevd.",
  "Delivery time window is required.": "Tidsvindu er påkrevd.",
  "Disassembly": "Demontering",
  "Discount": "Rabatt",
  "Discount (ex VAT)": "Rabatt (eks. MVA)",
  "Driver": "Sjåfør",
  "Driver info": "Sjåførinfo",
  "Enter a location": "Skriv inn adresse",
  "Enter a return location": "Skriv inn returadresse",
  "Enter a phone number or an email address.": "Skriv inn telefonnummer eller e-postadresse.",
  "Enter email": "Skriv inn e-post",
  "Email is too long.": "E-postadressen er for lang.",
  "Enter a valid email address.": "Skriv inn en gyldig e-postadresse.",
  "Enter phone": "Skriv inn telefon",
  "Editing order": "Redigerer bestilling",
  "Edit website": "Rediger nettside",
  "Extra": "Ekstra",
  "Extra (ex VAT)": "Ekstra (eks. MVA)",
  "Extra pickup": "Ekstra henting",
  "Failed to delete order": "Kunne ikke slette bestilling",
  "Files": "Filer",
  "Floor No.": "Etasje",
  From: "Fra",
  General: "Generelt",
  "Hide columns": "Skjul kolonner",
  Home: "Hjem",
  "Hours input": "Timer",
  "Info for the driver": "Info til sjåfør",
  Installation: "Montering",
  Language: "Språk",
  "Last edited": "Sist redigert",
  "License plate": "Skiltnummer",
  Lift: "Heis",
  "Loading...": "Laster...",
  "Loading catalog...": "Laster katalog...",
  "Loading order...": "Laster bestilling...",
  "Loading orders...": "Laster bestillinger...",
  "Model number": "Modellnummer",
  "Order number is required.": "Ordrenummer er pÃ¥krevd.",
  Next: "Neste",
  No: "Nei",
  "No attachments yet.": "Ingen vedlegg enda.",
  "No status change": "Ingen statusendring",
  "No subcontractor change": "Ingen underleverandørendring",
  "No installation options available.": "Ingen installasjonsalternativer for dette produktet.",
  "New order": "Ny bestilling",
  "No orders found": "Ingen bestillinger funnet",
  "No products selected.": "Ingen produkter valgt.",
  "No receipts yet.": "Ingen kvitteringer enda.",
  "No return options available.": "Ingen returalternativer tilgjengelig.",
  "No services selected for this product.": "Ingen tjenester valgt for dette produktet.",
  "No shop pickup address": "Ingen henteadresse fra butikk",
  "No utpakking / demontering options.": "Ingen alternativer for utpakking / demontering.",
  "Open": "Åpne",
  "Order changed": "Bestilling endret",
  "Optional": "Valgfritt",
  "Optional note": "Valgfritt notat",
  "Order created": "Bestilling opprettet",
  "Order no.": "Ordrenr.",
  "Order number": "Ordrenummer",
  Order: "Bestilling",
  Orders: "Bestillinger",
  "Orders per page": "Bestillinger per side",
  "Pallet quantity": "Antall paller",
  Phone: "Telefon",
  "Phone number contains invalid characters.": "Telefonnummeret inneholder ugyldige tegn.",
  "Phone number must be 7 to 20 characters.": "Telefonnummeret må være 7 til 20 tegn.",
  "Price ex. VAT": "Pris eks. MVA",
  "Pickup": "Henting",
  "Pickup address": "Henteadresse",
  "Pickup address is required.": "Henteadresse er påkrevd.",
  Previous: "Forrige",
  Products: "Produkter",
  "Product amount": "Antall produkter",
  "Request new function / bug fix": "Be om ny funksjon / meld feil",
  "Refresh": "Oppdater",
  "Reset Filters": "Nullstill filtre",
  Return: "Retur",
  "Return address": "Returadresse",
  "Return address is required.": "Returadresse er påkrevd.",
  Receipts: "Kvitteringer",
  "Save failed": "Kunne ikke lagre",
  "Saving...": "Lagrer...",
  Search: "Søk",
  "Search ID, name, phone, order no...": "Søk ID, navn, telefon, ordrenr...",
  Select: "Velg",
  Selected: "Valgt",
  "Second driver": "Andre sjåfør",
  selected: "valgt",
  Status: "Status",
  "Status notes": "Statusnotater",
  Store: "Butikk",
  Subcontractor: "Underleverandør",
  "Subcontractor minus": "Underleverandør minus",
  "Subcontractor plus": "Underleverandør pluss",
  "Subcontractor price": "Underleverandørpris",
  "Switch language": "Bytt språk",
  Submit: "Send inn",
  "This month": "Denne måneden",
  "This week": "Denne uken",
  "Time window": "Tidsvindu",
  To: "Til",
  Today: "I dag",
  Tomorrow: "I morgen",
  Total: "Total",
  "Total driving distance": "Total kjøreavstand",
  "Total incl. VAT": "Total inkl. MVA",
  "Type any number": "Skriv et tall",
  "Uploading...": "Laster opp...",
  "Unpacking / disassembly": "Utpakking / demontering",
  "Up to date": "Ingen endringer",
  "Update orders?": "Oppdater bestillinger?",
  "Updated": "Oppdatert",
  "Use new price": "Bruk ny pris",
  "User management": "Brukeradministrasjon",
  "VAT (25%)": "MVA (25%)",
  "Warning": "Advarsel",
  "Warning: delivery date is in the past": "Advarsel: leveringsdato er i fortiden",
  Yes: "Ja",
  "You do not have access to create orders.": "Du har ikke tilgang til å opprette bestillinger.",
  "failed to create order": "Kunne ikke opprette bestilling",
  "failed to load orders": "Kunne ikke laste bestillinger",
  "log out": "Logg ut",
  "Price Lists": "Prislister",
  Product: "Produkt",
  "No price lists assigned to your account.": "Ingen prislister er tildelt din konto.",
  "Product Options": "Produktalternativer",
  "Option Code": "Alternativkode",
  Label: "Betegnelse",
  "Price (NOK)": "Pris (NOK)",
  "Return Options": "Returalternativer",
  "Automatic XTRA": "Automatisk XTRA",
  "Utpakking / Demontering": "Utpakking / Demontering",
  "Something went wrong": "Noe gikk galt",
  "Failed to load price lists": "Kunne ikke laste prislister",
  "Failed to load price list": "Kunne ikke laste prisliste",
};

const NB_STATUS_LABELS: Record<string, string> = {
  active: "Aktiv",
  cancelled: "Kansellert",
  completed: "Fullført",
  confirmed: "Bekreftet",
  failed: "Feilet",
  invoiced: "Fakturert",
  paid: "Betalt",
  processing: "Behandles",
};

export function bookingText(locale: BookingUiLocale | undefined, text: string) {
  if (locale !== "nb") {
    return text;
  }

  return NB_TEXT[text] ?? text;
}

export function bookingStatusText(
  locale: BookingUiLocale | undefined,
  status: string,
) {
  if (locale !== "nb") {
    return status;
  }

  return NB_STATUS_LABELS[status.toLowerCase()] ?? status;
}
